export const actionTypes = {
  // DUMMY_STATE: 'DUMMY_STATE',
  LOAD_HOME_SCREEN_REQUEST: 'LOAD_HOME_SCREEN_REQUEST',
  LOAD_HOME_SCREEN_SUCCESS: 'LOAD_HOME_SCREEN_SUCCESS',
  SEARCH_MOVIE_REQUEST: 'SEARCH_MOVIE_REQUEST',
  SEARCH_MOVIE_REQUEST_SUCCESS: 'SEARCH_MOVIE_REQUEST_SUCCESS',
  SEARCH_MOVIE_REQUEST_ERROR: 'SEARCH_MOVIE_REQUEST_ERROR',
};
